[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.24", features = ["blocking"] }
scraper = "0.19.0"
html5ever = "0.26"
fastmurmur3 = "0.2.0"
regex = "1.10.3"
log = "0.4.21"
env_logger = "0.11.2"
url = "2.5.0"
