name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo snap install --edge --classic just
    - uses: actions/checkout@v3
    - name: Check formatting
      run: just fmt
    - name: Run clippy
      run: just clippy
    - name: Build
      run: just build
    - name: Run tests
      run: just test
